version: '3'
services:

  db:
    extends:
      file: docker-compose.yml
      service: db

  server:
    build: ./server
    image: leaf_api
    container_name: leaf_api_demo
    ports:
      - 5001:5001
    volumes:
      - ./server/keys:/.keys
      - ./server:/app
      - server-log:/logs
    environment:
      - LEAF_APP_DB=${LEAF_APP_DB}
      - LEAF_CLIN_DB=${LEAF_CLIN_DB}
      - LEAF_JWT_KEY_PW=${LEAF_JWT_KEY_PW}
      - UnsecuredIsAdmin=${UnsecuredIsAdminDev}
    networks:
      - leaf
    depends_on:
      - db

  ui-client:
    build:
      context: ./ui-client
      dockerfile: Dockerfile-dev
    container_name: leaf_ui
    ports:
      - 3000:3000
    volumes:
      - ./ui-client:/app
    networks:
      - leaf
    stdin_open: true
    depends_on:
      - db
      - server

networks:
  leaf:

volumes:
  server-log: